### ISSUE TITLE
TCGA Tissue Slide Images Not Downloadable

### ISSUE THREAD

**Issue by shuangyanl** [isb-cgc/readthedocs#570]
# System and Software
gsutil version: 4.61
google cloud SDK: 340.0.0
Operating system: Centos Linux 7

# Description
tried to use gsutil cp command to download TCGA svs image slides from the bucket gs://gdc-tcga-phs000178-open/, but got the "CommandException: No URLs matched" error.

# Reproduction
$ gsutil cp gs://gdc-tcga-phs000178-open/0ea22a61-446e-47d2-ba1c-a1b46e672df7/TCGA-B0-5713-01Z-00-DX1.afdee2d7-be99-4a3f-addf-b4942b891e7a.svs .

**Comment by DavidPotCanuck** [comment]
Hello.  

NCI has currently removed availability of those images.

NCI has requested that you reach out to:

https://gdc.cancer.gov/support to enquire the status of when those images will become available again.  They should be able to assist.

Please let us know if there is anything we can do to assist at ISB-CGC.  We appreciate you using our systems in the past and would welcome citations if you publish using our systems.

Thank you,

David

David Pot, Ph.D.
Director of Bioinformatics, Health Research Programs

T   571-454-0684 NEW | M   240.483.8604
david.pot@gdit.com
6003 Executive Blvd., Suite 400
Rockville, MD, 20852
www.gdit.com

**Comment by shuangyanl** [comment]
Hi David @DavidPotCanuck , thank you for following up this. I will contact the gdc helpdesk for checking the status.
